spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userReg
      username: yeganexelilova6466@gmail.com    # MongoDB username
      password: Zainayyyy6466     # MongoDB password
      authentication-database: admin  #Authentication database
      auto-index-creation: true   # Automatically create indexes
#      write-concern: NORMAL       # Write concern level (e.g., MAJORITY, NORMAL)
#      replica-set: <replica_set_name>  # Replica set name (if applicable)
#logging:
#  level:g
#    org.springframework.web: DEBUG
#
